version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket yifenghe2019 --output-template-file deploy.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - deploy.yaml
